### ISSUE TITLE
Todo for content changes for the first semester week of 2024

### ISSUE THREAD

**Issue by TobiasGrether** [fsr5-fhaachen/portals#660]
The following information is still missing from the respective working group reps:

- [ ]  Group Names for the Introductory Groups
- [ ] Number of desired groups for Introduction
- [ ] Number of desired groups for "Stadtrallye"
- [ ] Number of desired groups for "Kneipentour"
- [ ] Number of desired groups for "Hausführung"
- [ ] Number of desired groups for "Katerbrunch"
- [x] Ask if new Thursday Afternoon program needs registration, if yes add it to the seeders (@simonostendorf)
- [ ] Available Slots and number of available spots per Slot for the sports and culture program
- [x] create and seed telegram groups for "Stadtrallye" (@simonostendorf)
- [x] create and seed telegram groups for "Kneipentour" (@simonostendorf)
- [x] deploy to "erstiwoche.fsr5.de", URL fixed because it will be added to the introduction presentation (@simonostendorf)

**Comment by TobiasGrether** [comment]
Feedback for the house tour:

Info 200 -> 10 Groups 
ET 60      -> 5  Groups 
DIB 45     -> 3  Groups 
WI  45  -> 3  Groups

**Comment by TobiasGrether** [comment]
Feedback from the group phase: Keep group names

**Comment by TobiasGrether** [comment]
For the bar tour, the group wants 24 groups and that the registration from Monday 00:00 until wednesday 17:00, when the slot assignment will happen

**Comment by TobiasGrether** [comment]
For the city tour, they need 16 groups
